apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres.fullname" . -}}{{- .Values.db.dbPersistentVolumeClaimName }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.db.mountPath }}
