apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
  {{- include "postgres.labels" . | nindent 4 }}
spec:
  selector:
  {{- include "postgres.selectorLabels" . | nindent 6 }}
  ports:
    - name: http
      port: {{ .Values.db.servicePort }}
      targetPort: {{ .Values.db.containerPort }}
      protocol: TCP