apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sqlserver2019.fullname" . -}}-mssql
  labels:
    {{- include "sqlserver2019.labels" . | nindent 4}}
data:
  mssql.conf: |
    [EULA]
    accepteula = Y
    accepteulaml = Y
    
    [coredump]
    captureminiandfull = true
    coredumptype = full
    
    [hadr]
    hadrenabled = 1
    
    [language]
    lcid = 1033  
    
    [filelocation]
    defaultdatadir = /var/opt/mssql/userdata
    defaultlogdir = /var/opt/mssql/userlog    