apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  labels:
    {{- include "sqlserver2019.labels" . | nindent 4 }}
  annotations:
    volume.beta.kubernetes.io/storage-class: hostpath
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-userdb
  labels:
    {{- include "sqlserver2019.labels" . | nindent 4 }}
  annotations:
    volume.beta.kubernetes.io/storage-class: hostpath
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-log
  labels:
    {{- include "sqlserver2019.labels" . | nindent 4 }}  
  annotations:
    volume.beta.kubernetes.io/storage-class: hostpath
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-temp
  labels:
    {{- include "sqlserver2019.labels" . | nindent 4 }}  
  annotations:
    volume.beta.kubernetes.io/storage-class: hostpath
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi