apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sqlserver2019.fullname" . -}}-mssql-secret
  labels:
    {{- include "sqlserver2019.labels" . | nindent 4}}
type: Opaque
data:
  sa_password: {{ .Values.db.sa_password | b64enc | quote }}